// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MokaCafe.Data;

#nullable disable

namespace MokaCafe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MokaCafe.Models.CauHinhHeThong", b =>
                {
                    b.Property<int>("MaCauHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCauHinh"));

                    b.Property<bool>("BaoCaoCuoiNgay")
                        .HasColumnType("bit");

                    b.Property<bool>("CanhBaoHangHet")
                        .HasColumnType("bit");

                    b.Property<bool>("DangMoCua")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DonToiThieuMienPhi")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("GioMoCua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HoTroChuyenKhoan")
                        .HasColumnType("bit");

                    b.Property<bool>("HoTroMoMo")
                        .HasColumnType("bit");

                    b.Property<bool>("HoTroTheTinDung")
                        .HasColumnType("bit");

                    b.Property<bool>("HoTroTienMat")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhamViGiaoHang_km")
                        .HasColumnType("int");

                    b.Property<decimal>("PhiGiaoHangCoBan")
                        .HasColumnType("decimal(18,0)");

                    b.Property<bool>("SMSThongBaoKH")
                        .HasColumnType("bit");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ThongBaoDonMoi")
                        .HasColumnType("bit");

                    b.HasKey("MaCauHinh");

                    b.ToTable("CauHinhHeThong");
                });

            modelBuilder.Entity("MokaCafe.Models.CheBien", b =>
                {
                    b.Property<int>("MaCheBien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCheBien"));

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCheBien");

                    b.HasIndex("MaDonHang")
                        .IsUnique();

                    b.HasIndex("MaNhanVien");

                    b.ToTable("CheBien");
                });

            modelBuilder.Entity("MokaCafe.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("GhiChuMon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaMon")
                        .HasColumnType("int");

                    b.Property<string>("MucDa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("MokaCafe.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaGioHang")
                        .HasColumnType("int");

                    b.Property<int>("MaMon")
                        .HasColumnType("int");

                    b.Property<string>("MucDa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaGioHang");

                    b.HasIndex("MaMon");

                    b.ToTable("ChiTietGioHang");
                });

            modelBuilder.Entity("MokaCafe.Models.ChucVuNhanVien", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucVu"));

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVuNhanVien");
                });

            modelBuilder.Entity("MokaCafe.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<bool>("KichHoat")
                        .HasColumnType("bit");

                    b.Property<string>("MaDanhMucJS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("MokaCafe.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("DiaChiGiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNguoiNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDonHangHienThi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("MaVanChuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhiGiaoHang")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("SoDienThoaiGiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TamTinh")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("ThoiGianDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaDonHangHienThi")
                        .IsUnique();

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("MokaCafe.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MaPhien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaGioHang");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("MokaCafe.Models.HoSoNhanVien", b =>
                {
                    b.Property<int>("MaHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSo"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiLamViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHoSo");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique();

                    b.ToTable("HoSoNhanVien");
                });

            modelBuilder.Entity("MokaCafe.Models.MonAn", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMon"));

                    b.Property<bool>("CoTuyChonDa")
                        .HasColumnType("bit");

                    b.Property<bool>("CoTuyChonDuong")
                        .HasColumnType("bit");

                    b.Property<string>("Emoji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int?>("MaMonJS")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaMon");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("MonAn");
                });

            modelBuilder.Entity("MokaCafe.Models.MonBanChay", b =>
                {
                    b.Property<int>("MaMonBanChay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMonBanChay"));

                    b.Property<decimal>("DoanhThu")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("MaMon")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.Property<int>("XepHang")
                        .HasColumnType("int");

                    b.HasKey("MaMonBanChay");

                    b.HasIndex("MaMon");

                    b.ToTable("MonBanChay");
                });

            modelBuilder.Entity("MokaCafe.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KichHoat")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("MokaCafe.Models.NguyenLieu", b =>
                {
                    b.Property<int>("MaNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguyenLieu"));

                    b.Property<string>("DonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoLuongHienTai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoLuongToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguyenLieu");

                    b.ToTable("NguyenLieu");
                });

            modelBuilder.Entity("MokaCafe.Models.NhatKyHoatDong", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("DuLieuLienQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHanhDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("NhatKyHoatDong");
                });

            modelBuilder.Entity("MokaCafe.Models.NhatKyKho", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("LoaiGiaoDich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGhiNhan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoLuongSau")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoLuongThayDoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoLuongTruoc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaNguyenLieu");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("NhatKyKho");
                });

            modelBuilder.Entity("MokaCafe.Models.PhanHoi", b =>
                {
                    b.Property<int>("MaPhanHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanHoi"));

                    b.Property<string>("ChuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhanHoi");

                    b.ToTable("PhanHoi");
                });

            modelBuilder.Entity("MokaCafe.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDonHang")
                        .IsUnique();

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("MokaCafe.Models.ThongTinKhachHang", b =>
                {
                    b.Property<int>("MaThongTin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongTin"));

                    b.Property<string>("GhiChuNoiBo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LaKhachThanThiet")
                        .HasColumnType("bit");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGheGanNhat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongChiTieu")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("TongDonHang")
                        .HasColumnType("int");

                    b.HasKey("MaThongTin");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique();

                    b.ToTable("ThongTinKhachHang");
                });

            modelBuilder.Entity("MokaCafe.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaVaiTroJS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("MokaCafe.Models.CheBien", b =>
                {
                    b.HasOne("MokaCafe.Models.DonHang", "DonHang")
                        .WithOne("CheBien")
                        .HasForeignKey("MokaCafe.Models.CheBien", "MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MokaCafe.Models.NguoiDung", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("MokaCafe.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("MokaCafe.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MokaCafe.Models.MonAn", "MonAn")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("MokaCafe.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("MokaCafe.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MokaCafe.Models.MonAn", "MonAn")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("MokaCafe.Models.DonHang", b =>
                {
                    b.HasOne("MokaCafe.Models.NguoiDung", "KhachHang")
                        .WithMany("DonHangKhach")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MokaCafe.Models.NguoiDung", "NhanVien")
                        .WithMany("DonHangNhanVien")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("MokaCafe.Models.GioHang", b =>
                {
                    b.HasOne("MokaCafe.Models.NguoiDung", "NguoiDung")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaNguoiDung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("MokaCafe.Models.HoSoNhanVien", b =>
                {
                    b.HasOne("MokaCafe.Models.ChucVuNhanVien", "ChucVuNhanVien")
                        .WithMany("HoSoNhanViens")
                        .HasForeignKey("MaChucVu");

                    b.HasOne("MokaCafe.Models.NguoiDung", "NguoiDung")
                        .WithOne("HoSoNhanVien")
                        .HasForeignKey("MokaCafe.Models.HoSoNhanVien", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVuNhanVien");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("MokaCafe.Models.MonAn", b =>
                {
                    b.HasOne("MokaCafe.Models.DanhMuc", "DanhMuc")
                        .WithMany("MonAns")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("MokaCafe.Models.MonBanChay", b =>
                {
                    b.HasOne("MokaCafe.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("MokaCafe.Models.NguoiDung", b =>
                {
                    b.HasOne("MokaCafe.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("MokaCafe.Models.NhatKyHoatDong", b =>
                {
                    b.HasOne("MokaCafe.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("MokaCafe.Models.NhatKyKho", b =>
                {
                    b.HasOne("MokaCafe.Models.NguyenLieu", "NguyenLieu")
                        .WithMany("NhatKyKhos")
                        .HasForeignKey("MaNguyenLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MokaCafe.Models.NguoiDung", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguyenLieu");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("MokaCafe.Models.ThanhToan", b =>
                {
                    b.HasOne("MokaCafe.Models.DonHang", "DonHang")
                        .WithOne("ThanhToan")
                        .HasForeignKey("MokaCafe.Models.ThanhToan", "MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("MokaCafe.Models.ThongTinKhachHang", b =>
                {
                    b.HasOne("MokaCafe.Models.NguoiDung", "NguoiDung")
                        .WithOne("ThongTinKhachHang")
                        .HasForeignKey("MokaCafe.Models.ThongTinKhachHang", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("MokaCafe.Models.ChucVuNhanVien", b =>
                {
                    b.Navigation("HoSoNhanViens");
                });

            modelBuilder.Entity("MokaCafe.Models.DanhMuc", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("MokaCafe.Models.DonHang", b =>
                {
                    b.Navigation("CheBien");

                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("MokaCafe.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("MokaCafe.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("MokaCafe.Models.NguoiDung", b =>
                {
                    b.Navigation("DonHangKhach");

                    b.Navigation("DonHangNhanVien");

                    b.Navigation("GioHangs");

                    b.Navigation("HoSoNhanVien");

                    b.Navigation("ThongTinKhachHang");
                });

            modelBuilder.Entity("MokaCafe.Models.NguyenLieu", b =>
                {
                    b.Navigation("NhatKyKhos");
                });

            modelBuilder.Entity("MokaCafe.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
