# ===== MS SQL SERVER CONFIG =====
spring.datasource.url=jdbc:sqlserver://MSI:1433;databaseName=CinemaDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===== JPA / HIBERNATE =====
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===== JSP VIEW RESOLVER =====
# ===== JSP VIEW RESOLVER =====
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ===== JSP CONFIG - RẤT QUAN TRỌNG =====
server.servlet.jsp.init-parameters.development=true
server.servlet.jsp.init-parameters.keepgenerated=true
server.servlet.jsp.init-parameters.trimSpaces=true
spring.mvc.static-path-pattern=/static/**

# ===== STATIC RESOURCES =====
spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:src/main/webapp/,/WEB-INF/static/

# Tắt cache JSP
spring.mvc.view.resolver.cache=false
server.error.include-message=always
server.error.include-stacktrace=always
logging.level.org.springframework.security=DEBUG
logging.level.com.cinema=DEBUG

